Fix / remove subscribe to campaign
trompamusic/trompa-campaign-manager pull request #33
Opened 2021-03-18 13:31 UTC by demmyhonore

This PR removes the subscribe to campaign feature on the active campaign page. 

JIRA: TROM-1122

2021-03-19 08:59 UTC, royschut requested changes
Nice cleanup. There's also a 'subscribe' button on the ActiveCampaign component, and you might want to remove it from the campaign.json translation as well.

2021-03-19 09:48 UTC, royschut approved these changes

2021-03-19 10:37 UTC, ChristiaanScheermeijer approved these changes
LGTM!

2021-04-30 15:32 UTC, demmyhonore commented
Zit al in code.

2021-04-30 15:32 UTC, closed without merging